name: UUIDResolver
main: com.localchum.uuidresolver.bukkit.UuidResolverBukkit
version: 2.0
author: LocalChum
description: Enables the forward and backward resolution of Mojang UUIDs, with both online and offline support
load: STARTUP

commands:
  uuidresolver:
    usage: /uuidresolver <lookup-sync <name|uuid>|lookup-any <name|uuid>|bench|stats|purge>
    description: UuidResolver Administrative Command
